### ISSUE TITLE
self.config.min_pattern_support in breds_parallel.py clarification

### ISSUE THREAD

**Issue by zqyeo** [davidsbatista/BREDS#14]
Hi, I'd like to check on the variable self.config.min_pattern_support.

In line 293 (breds_parallel.py), the check for len(p.tuples) > self.config.min_pattern_support occurs under the if condition of len(self.patterns) == 0

However, under the else case, there is no such checks to remove patterns with tuples less than the min support. Is this deliberate by design? Otherwise, should the check also be done for len(self.patterns) != 0 too?

Thank you.

**Comment by davidsbatista** [comment]
Hi @zqyeo 

I've decided to remove the parallel version since it was something experimental, and it was non-deterministic, giving very different results in different runs, and mostly giving different results from the main idea.

If I have time I will explore/think about how to optimize the clustering algorithm in a different way.
