### ISSUE TITLE
Question about passive voice

### ISSUE THREAD

**Issue by airship-explorer** [davidsbatista/BREDS#15]
In your paper "Semi-Supervised Bootstrapping of Relationship Extractors with Distributional Semantics", you said "BREDS also tries to identify the passive voice using part-of-speech (PoS) tags ,..., it will swap the order of the entities when producing a relational triple". 

But I can't find this process in your code. **If BREDS detect the passive voice and swap the entities, about the words before the first entity and words after the second entity?** Can you give 
me some advice? Thank you!

**Comment by davidsbatista** [comment]
You can see the code that detects the passive voice here:

https://github.com/davidsbatista/BREDS/blob/master/breds/reverb.py#L277

It's a bit messy and I plant to change it so it uses the NLTK's RegexpParser, instead of long list of regexes and if statements,  like I did here:

http://www.davidsbatista.net/blog/2017/05/08/ReVerb/

The before and after words remain the same, it's only the relationship that changes directions, see examples in the paper.
